stages:
  train:
    cmd: >-
      python train.py
      --num_classes ${train.num_classes}
      --pretrained_on_ImageNet
      --fold ${train.fold}
      --dataset ${train.dataset}
      --gt ${train.gt}
      --outdir ${train.outdir}
      --epochs ${train.epochs}
      --seed ${base.random_seed}
    deps:
    - data/train
    - train.py
    params:
    - base
    - train
    outs:
    - models/model_best.pt
  evaluate:
    cmd: >-
      python predict.py
      --num_classes ${train.num_classes}
      --dataset ${evaluate.dataset}
      --gt ${evaluate.gt}
      --single_model_path ${train.outdir}/model_best.pt
    deps:
    - data/test
    - predict.py
    - models/model_best.pt
    params:
    - base
    - train
    - evaluate
  export:
    cmd: >-
      python export.py
      --single_model_path ${train.outdir}/model_best.pt
      --outdir ${export.outdir}
    deps:
    - export.py
    - models/model_best.pt
    params:
    - base
    - train
    - export
    outs:
    - models/model_best.onnx
    - models/model_best.pb
  tensorflowjs:
    cmd: >-
      tensorflowjs_converter
      --input_format=tf_saved_model
      --output_node_names=tfjs_layers_model
      --saved_model_tags=serve
      models/model_best.pb
      models/tfjs
    deps:
    - models/model_best.pb
    params:
    - base
    outs:
    - models/tfjs
